name: ADES110

on:
  workflow_dispatch:
    inputs:
      name:
        default: "World"
jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        uses: Amadevus/pwsh-script@v2
        with:
          script: |
            Write-Output 'Hello ${{ inputs.name }}'