name: ADES100
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Apply env var fix
        uses: ./env-fix-action
        run: |
            echo 'Hello ${{ inputs.name }}'
