name: ADES111

on: workflow_dispatch

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        uses: mikefarah/yq@master
        with:
          cmd: yq '${{ inputs.query }}' 'config.yml'