name: ADES103

on: workflow_dispatch

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        uses: roots/issue-closer-action@v1
        with:
          pr-close-message: Closing ${{ github.event.issue.title }}
          issue-pattern: ".*guidelines for Contributing.*"
