name: ADES104

on: workflow_dispatch

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        uses: sergeysova/jq-action@v2
        with:
          cmd: jq .version ${{ github.event.inputs.file }} -r 