name: ADES101

on: workflow_dispatch

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        uses: actions/github-script@v6
        with:
          script: console.log('Hello ${{ inputs.name }}')

        
