name: Multiproblem

on: workflow_dispatch

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        uses: roots/issue-closer-action@v1
        with:
          issue-close-message: Closing ${{ github.event.issue.title }}
      - name: ADES101
        uses: actions/github-script@v6
        with:
          script: console.log('Hello ${{ inputs.name }}')